DO NOT SEND ME ANY JUNK EMAIL SEE
http://www.eskimo.com/~delisle/warning.letter.htm

If you send me junk E-mail, I may come and hurt or kill your business, I'll sue you, I'll file complaints to the AG against you.

 
 
 \      |    \    BRITISH COLUMBIA    CANADA                        | ALBERTA
  |     |  .  |o Vancouver                                          |   
  |      \ ;  |_____________________________________________________|________
   \ ___ /     \o Bellingham                   o Colville   | 
            ,.  |                   o Okanogan    |         |
  _________ .,  |o Burlington                     |         | 
  \        | | |                    o Chelan      |         |
   |       | ;  \o|Everett                     o Spokane    |
   |        \ . |o|Seattle o Snoqualmie           |         |
   >        <   > |         WASHINGTON            |o Lewiston\_   MONTANA
   \         \_/ o Tacoma   (Center of the known  |            \
    |         X * Olympia      World)             |             |
    \           o Centralla   o Yakima            |             \
     |             o Longview                     |              \
     \__                              o WallaWalla|                -
      / \__            ___________________________|   IDAHO          \_
     |     \__________/            o The Dalls    > 
     |             o Portland   	          | 
     /  o Tillamook       OREGON                  |
    |                                             |      
    |            o Eugene       o Bend            |          o Boise  
You have new mail.
