<?xml version='1.0'?>
 <!-- Generated by Dobe's Resume Wizard for XML --> 
 <xsl:stylesheet 
      xmlns:xsl='http://www.w3.org/TR/WD-xsl' 
      xmlns:xtxsl='http://www.w3.org/XSL/Transform/1.0' 
      xmlns:msxsl='http://www.w3.org/TR/WD-xsl' 
      xmlns:fo='http://www.w3.org/1999/XSL/Format' 
       result-ns=''>
  <xsl:template match=' / '>
    <html> 
      <head>
        <title><xsl:value-of select='resume/title' /></title>
       <style type='text/css'>
         a:link {color: blue; text-decoration:none;}
         a:visited {color:blue; text-decoration:none;}
         a:active {color:red; text-decoration:none background:lightgreen;}
         body {background:ghostwhite; font-family: ariel | helvetica | serif;}
         table {background:ghostwhite;}
         h1 {font-size:150%; color:black;}
         h2 {font-size:115%; color:black;}
         div.objectiveMain {font-size:120%; color:black; font-weight:bold; vertical-align:top;}
         div.objectiveSkillset {font-size:100%; color:black; vertical-align:top;}
         h1.Name {font-size:200%; color:black;}
         td.Header {font-style:italic; font-size:80%; color:black; vertical-align:top;}
         td.GPA {font-size:80%; color:black; vertical-align:top;}
         td.College {font-size:100%; color:black; font-weight:bold; vertical-align:top;}
         td.CollegeName {font-size:110%; color:black; font-weight:bold; vertical-align:top;}
         td.CompanyName {font-size:110%; color:black; font-weight:bold; vertical-align:top;}
         td.CollegeNotes {font-size:90%; color:black; vertical-align:top;}
         td.CompanyNotes {font-size:90%; color:black; vertical-align:top;}
         td.CollegeYears {font-size:90%; color:black; vertical-align:top;}
         td.CompanyYears {font-size:90%; color:black; vertical-align:top;}
         td.Company {font-size:100%; color:black; font-weight:bold; vertical-align:top;}
         td.CompanyPosition {font-size:100%; color:black; font-weight:bold; vertical-align:top;}
         td.distinctionNotes {font-size:90%; color:black; vertical-align:top;}
       </style>
      </head>
      <body>
       <table border='0' width='90%'>
        <tr align='right'>
         <td>&#160;
         </td>
         <td class='header'>
<!-- Italic, right-aligned, address, phone, email -->
        <xsl:value-of select='resume/header/street' /><br />
        <xsl:value-of select='resume/header/city' />,
        <xsl:value-of select='resume/header/state' />.
        <xsl:value-of select='resume/header/zipCode' /><br />
        <xsl:value-of select='resume/header/phone' /><br />
        <xsl:value-of select='resume/header/email' /><br /><br />
         </td>
        </tr>
<!-- Big font for name, with <hr> -->
        <tr align='left'>
         <td colspan='2'>
        <h1 class='Name'><xsl:value-of select='resume/name' />
        <hr width='100%' />
        </h1>
         </td>
         <td>
         </td>
        </tr>
        <tr valign='top' height='100'>
<!-- Begin OBJECTIVE Table -->
         <td>
        <h2><b>Objective:</b></h2>
         </td>
         <td>
         <table border='0' cellspacing='0' cellpadding='0' width='100%'>
          <tr>
           <td>
        <div class='objectiveMain'>
         <xsl:value-of select='resume/docbody/objective/primary' />
        </div>
         <xsl:value-of select='resume/docbody/objective/secondary' /><br />
         <xsl:value-of select='resume/docbody/objective/location' /><br />
         <xsl:value-of select='resume/docbody/objective/note1' /><br />
         <xsl:value-of select='resume/docbody/objective/note2' />
 
           </td>
          </tr>
         </table>
         </td>
        </tr>
<!-- Begin EDUCATION Table -->
        <tr valign='top' height='150'>
         <td>
<!--  &horizontalTab; = &#09;  -->
        <h2><b>Education:</b></h2>
         </td>
         <td>
        <!-- Begin XSL:FOR-EACH Element for EDUCATION   -->
        <xsl:for-each select='resume/docbody/education/college'>
 
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td class='CollegeName' width='60%'>
             <xsl:value-of select='././collegeName' />
           </td>
           <td class='College' width='25%' align='left'>
            <xsl:value-of select='././townState' />
           </td>
           <td class='CollegeYears' width='15%' align='right'>
            <xsl:value-of select='././years' />
 
           </td>
          </tr>
         </table>
 
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td width='70%' align='left'>
            <b><xsl:value-of select='././program' /></b>
           </td>
           <td class='GPA' width='30%' align='right'>
        <xsl:value-of select='././program/@GPA/text()' />&#160;GPA
           </td>
          </tr>
         </table>
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td class='CollegeNotes' align='left'>
            <xsl:value-of select='././note1' />
           </td>
          </tr>
 
         </table>
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td class='CollegeNotes' align='left'>
            <xsl:value-of select='././note2' />
 
           </td>
          </tr>
         </table>
 
        <xsl:apply-templates />
        </xsl:for-each>
        <!-- End XSL:FOR-EACH Element   -->
         </td>
        </tr>
 
<!-- Begin EXPERIENCE Table -->
        <tr valign='top' height='150'>
         <td>
        <h2><b>Experience:</b></h2>
         </td>
         <td>
        <!-- Begin XSL:FOR-EACH Element for EXPERIENCE  -->
        <xsl:for-each select='resume/docbody/experience/company'>
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td class='CompanyName' width='60%' valign='top'>
             <xsl:value-of select='././companyName/text()' />
           </td>
          <td class='Company' width='25%' align='left'>
            <xsl:value-of select='././townState' />
           </td>
           <td class='CompanyYears' width='15%' align='right'>
            <xsl:value-of select='././years' />
           </td>
          </tr>
         </table>
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td class='CompanyPosition' align='left'>
 
            <xsl:value-of select='././position' />
           </td>
          </tr>
         </table>
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td class='CompanyNotes' align='left'>
 
            <xsl:value-of select='././note1' />
           </td>
          </tr>
 
        </table>
         <table border='0' cellspacing='2' cellpadding='2' width='90%'>
          <tr>
           <td class='CompanyNotes' align='left'>
            <xsl:value-of select='././note2' />
           </td>
          </tr>
         </table>
        <xsl:apply-templates />
        </xsl:for-each>
        <!-- End XSL:FOR-EACH Element   -->
        </td>
        </tr>
<!-- Begin DISTINCTIONS Table -->
        <tr valign='top' height='150'>
         <td>
        <h2><b>Distinctions:</b></h2>
 
         </td>
         <td>
       <table border='0' align='left' cellspacing='1' cellpadding='3' >
        <tr>
         <td class='distinctionNotes'>
           <xsl:value-of select='resume/docbody/experience/distinctions/note1' />  <br />
           <xsl:value-of select='resume/docbody/experience/distinctions/note2' />  <br />
        <xsl:apply-templates />
        </td>
        </tr>
       </table>
 
        </td>
        </tr>
 
       </table>
 
      </body>
    </html>
        <xsl:apply-templates />
  </xsl:template>
 </xsl:stylesheet>

