package ch11;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class Calculator {
	double fieldNum1 = 0;
	protected transient java.beans.PropertyChangeSupport propertyChange = new java.beans.PropertyChangeSupport(this);

	double fieldNum2 = 0;
	double fieldResult = 0;
	public double fieldResultMPH;
/**
 * Performs the add method.
 */
public void add() {
	/* Perform the add method. */
	setResult(getNum1() + getNum2());
	return;
}
/**
 * The addPropertyChangeListener method was generated to support the propertyChange field.
 */
public synchronized void addPropertyChangeListener(java.beans.PropertyChangeListener listener) {
	propertyChange.addPropertyChangeListener(listener);
}
/**
 * Performs the divide method.
 */
public void divide() {
	/* Perform the divide method. */
	setResult(getNum1() / getNum2());	
	return;
}
/**
 * The firePropertyChange method was generated to support the propertyChange field.
 */
public void firePropertyChange(String propertyName, Object oldValue, Object newValue) {
	propertyChange.firePropertyChange(propertyName, oldValue, newValue);
}
/**
 * Insert the method's description here.
 * Creation date: (3/27/2001 2:39:51 PM)
 * @return double
 */
public double getFieldResultMPH() {
	return fieldResultMPH;
}
/**
 * Gets the num1 property (double) value.
 * @return The num1 property value.
 * @see #setNum1
 */
public double getNum1() {
	/* Returns the num1 property value. */
	return fieldNum1;
}
/**
 * Gets the num2 property (double) value.
 * @return The num2 property value.
 * @see #setNum2
 */
public double getNum2() {
	/* Returns the num2 property value. */
	return fieldNum2;
}
/**
 * Gets the result property (double) value.
 * @return The result property value.
 * @see #setResult
 */
public double getResult() {
	/* Returns the result property value. */
	return fieldResult;
}
/**
 * Performs the multiply method.
 */
public void multiply() {
	/* Perform the multiply method. */
	setResult(getNum1() * getNum2());	
	return;
}
/**
 * The removePropertyChangeListener method was generated to support the propertyChange field.
 */
public synchronized void removePropertyChangeListener(java.beans.PropertyChangeListener listener) {
	propertyChange.removePropertyChangeListener(listener);
}
/**
 * Insert the method's description here.
 * Creation date: (3/27/2001 2:39:51 PM)
 * @param newFieldResultMPH double
 */
public void setFieldResultMPH(double newFieldResultMPH) {
		/* Get the old property value for fire property change event. */
	double oldValue = fieldResultMPH;
	/* Set the result property (attribute) to the new value. */
	fieldResultMPH = newFieldResultMPH;
	/* Fire (signal/notify) the result property change event. */
	firePropertyChange("resultMPH", new Double(oldValue), new Double(newFieldResultMPH));
	return;
}
/**
 * Sets the num1 property (double) value.
 * @param num1 The new value for the property.
 * @see #getNum1
 */
public void setNum1(double num1) {
	/* Get the old property value for fire property change event. */
	double oldValue = fieldNum1;
	/* Set the num1 property (attribute) to the new value. */
	fieldNum1 = num1;
	/* Fire (signal/notify) the num1 property change event. */
	firePropertyChange("num1", new Double(oldValue), new Double(num1));
	return;
}
/**
 * Sets the num2 property (double) value.
 * @param num2 The new value for the property.
 * @see #getNum2
 */
public void setNum2(double num2) {
	/* Get the old property value for fire property change event. */
	double oldValue = fieldNum2;
	/* Set the num2 property (attribute) to the new value. */
	fieldNum2 = num2;
	/* Fire (signal/notify) the num2 property change event. */
	firePropertyChange("num2", new Double(oldValue), new Double(num2));
	return;
}
/**
 * Sets the result property (double) value.
 * @param result The new value for the property.
 * @see #getResult
 */
public void setResult(double result) {
	/* Get the old property value for fire property change event. */
	double oldValue = fieldResult;
	/* Set the result property (attribute) to the new value. */
	fieldResult = result;
	fieldResultMPH = (result * 1.15);
	/* Fire (signal/notify) the result property change event. */
	firePropertyChange("result", new Double(oldValue), new Double(result));
	return;
}
/**
 * Performs the add method.
 */
public void speed() {
	/* Perform the speed calculation */
	setResult(getNum2() * java.lang.Math.sqrt(getNum1()));;
	return;
}
/**
 * Insert the method's description here.
 * Creation date: (3/30/2001 2:29:38 PM)
 */
public void speedMPH() {
	
	setFieldResultMPH(getNum2() * java.lang.Math.sqrt(getNum1()));;
	
	}
/**
 * Performs the subtract method.
 */
public void subtract() {
	/* Perform the subtract method. */
	setResult(getNum1() - getNum2());	
	return;
}
}
