package ch11;

import java.applet.*;
import java.awt.*;
/**
 * This applet was generated by a SmartGuide.
 * 
 */
public class HulSpeed extends Applet implements java.awt.event.ActionListener, java.awt.event.FocusListener, java.awt.event.MouseListener, java.awt.event.TextListener, java.beans.PropertyChangeListener {
	private Calculator ivjCalculator = null;
	private boolean ivjConn0Aligning = false;
	private boolean ivjConn1Aligning = false;
	private Button ivjAddButton = null;
	private Button ivjDivideButton = null;
	private Button ivjMultiplyButton = null;
	private Button ivjSubtactButton = null;
	private Button ivjSpeedCalcButton = null;
	private TextField ivjFactorField = null;
	private Label ivjFactorFieldLable = null;
	private Label ivjLenghtAtWaterLineLable = null;
	private TextField ivjLengthAtWaterLineField = null;
	private TextField ivjSpeedField = null;
	private Label ivjLenghtAtWaterLineLable2 = null;
	private Label ivjSpeedFieldLabel2 = null;
	private Label ivjSpeedFieldLabel1 = null;
	private Label ivjSpeedFieldLabel22 = null;
	private Label ivjSpeedFieldLabel12 = null;
	protected transient java.beans.PropertyChangeSupport propertyChange;
	private TextField ivjSpeedFieldMPH = null;
	private TextField ivjmsgField = null;
	private Label ivjblank = null;
	private Label ivjSpeedMPHmsg = null;
	private Label ivjSpeedKnotsMsg = null;
	private Label ivjFactorMsg = null;
	private Label ivjLWLmsg = null;
	private Label ivjCalculateButtonMouseMsg = null;
	private Label ivjCalculateButtonTabMsg = null;
/**
 * Method to handle events for the ActionListener interface.
 * @param e java.awt.event.ActionEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void actionPerformed(java.awt.event.ActionEvent e) {
	// user code begin {1}
	// user code end
	if (e.getSource() == getDivideButton()) 
		conn6(e);
	if (e.getSource() == getMultiplyButton()) 
		conn5(e);
	if (e.getSource() == getSubtactButton()) 
		conn4(e);
	if (e.getSource() == getAddButton()) 
		connEtoM1(e);
	if (e.getSource() == getSpeedCalcButton()) 
		connEtoM2(e);
	// user code begin {2}
	// user code end
}
/**
 * The addPropertyChangeListener method was generated to support the propertyChange field.
 */
public synchronized void addPropertyChangeListener(java.beans.PropertyChangeListener listener) {
	getPropertyChange().addPropertyChangeListener(listener);
}
/**
 * This method was created by a SmartGuide.
 */
private void adjustColor(Color aColor ) {
	if ((new Double(getSpeedField().getText())).doubleValue() < 0.)
		getSpeedField().setForeground(aColor);
	else	
		getSpeedField().setForeground(Color.black);
	return;
}
/**
 * conn0SetSource:  (TextField1.text <--> Calculator.num1)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void conn0SetSource() {
	/* Set the source from the target */
	try {
		if (ivjConn0Aligning == false) {
			// user code begin {1}
			// user code end
			ivjConn0Aligning = true;
			getLengthAtWaterLineField().setText(String.valueOf(getCalculator().getNum1()));
			// user code begin {2}
			// user code end
			ivjConn0Aligning = false;
		}
	} catch (java.lang.Throwable ivjExc) {
		ivjConn0Aligning = false;
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * conn0SetTarget:  (TextField1.text <--> Calculator.num1)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void conn0SetTarget() {
	/* Set the target from the source */
	try {
		if (ivjConn0Aligning == false) {
			// user code begin {1}
			// user code end
			ivjConn0Aligning = true;
			getCalculator().setNum1(new Double(getLengthAtWaterLineField().getText()).doubleValue());
			// user code begin {2}
			// user code end
			ivjConn0Aligning = false;
		}
	} catch (java.lang.Throwable ivjExc) {
		ivjConn0Aligning = false;
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * conn1SetSource:  (TextField2.text <--> Calculator.num2)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void conn1SetSource() {
	/* Set the source from the target */
	try {
		if (ivjConn1Aligning == false) {
			// user code begin {1}
			// user code end
			ivjConn1Aligning = true;
			getFactorField().setText(String.valueOf(getCalculator().getNum2()));
			// user code begin {2}
			// user code end
			ivjConn1Aligning = false;
		}
	} catch (java.lang.Throwable ivjExc) {
		ivjConn1Aligning = false;
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * conn1SetTarget:  (TextField2.text <--> Calculator.num2)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void conn1SetTarget() {
	/* Set the target from the source */
	try {
		if (ivjConn1Aligning == false) {
			// user code begin {1}
			// user code end
			ivjConn1Aligning = true;
			getCalculator().setNum2(new Double(getFactorField().getText()).doubleValue());
			// user code begin {2}
			// user code end
			ivjConn1Aligning = false;
		}
	} catch (java.lang.Throwable ivjExc) {
		ivjConn1Aligning = false;
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * conn4:  (Button11.action.actionPerformed(java.awt.event.ActionEvent) --> Calculator.subtract())
 * @param arg1 java.awt.event.ActionEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void conn4(java.awt.event.ActionEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		getCalculator().subtract();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * conn5:  (Button12.action.actionPerformed(java.awt.event.ActionEvent) --> Calculator.multiply())
 * @param arg1 java.awt.event.ActionEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void conn5(java.awt.event.ActionEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		getCalculator().multiply();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * conn6:  (Button13.action.actionPerformed(java.awt.event.ActionEvent) --> Calculator.divide())
 * @param arg1 java.awt.event.ActionEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void conn6(java.awt.event.ActionEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		getCalculator().divide();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC1:  (SpeedField.text.textValueChanged(java.awt.event.TextEvent) --> HulSpeed.speedField_TextValueChanged1(Ljava.awt.event.TextEvent;)V)
 * @param arg1 java.awt.event.TextEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC1(java.awt.event.TextEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedField_TextValueChanged1(arg1);
		connEtoM3();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC10:  (SpeedFieldMPH.mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed.speedFieldMPH_MouseEntered1(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC10(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedFieldMPH_MouseEntered1(arg1);
		connEtoM4();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC11:  (LengthAtWaterLineField.focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed.lengthAtWaterLineField_FocusLost1(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC11(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.lengthAtWaterLineField_FocusLost1(arg1);
		connEtoM13();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC12:  (FactorField.focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed.factorField_FocusGained(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC12(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.factorField_FocusGained(arg1);
		connEtoM15();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC13:  (FactorField.focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed.factorField_FocusLost(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC13(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.factorField_FocusLost(arg1);
		connEtoM14();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC14:  (SpeedField.focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed.speedField_FocusGained(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC14(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedField_FocusGained(arg1);
		connEtoM16();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC15:  (SpeedField.focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed.speedField_FocusLost(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC15(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedField_FocusLost(arg1);
		connEtoM17();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC16:  (SpeedFieldMPH.focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed.speedFieldMPH_FocusGained(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC16(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedFieldMPH_FocusGained(arg1);
		connEtoM18();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC17:  (SpeedFieldMPH.focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed.speedFieldMPH_FocusLost(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC17(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedFieldMPH_FocusLost(arg1);
		connEtoM19();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC18:  (SpeedCalcButton.mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed.speedCalcButton_MouseEntered(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC18(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedCalcButton_MouseEntered(arg1);
		connEtoM20();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC19:  (SpeedFieldMPH.mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed.speedFieldMPH_MouseExited1(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC19(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedCalcButton_MouseExited(arg1);
		connEtoM21();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC2:  (LengthAtWaterLineField.focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed.lengthAtWaterLineField_FocusGained3(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC2(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.lengthAtWaterLineField_FocusGained3(arg1);
		connEtoM12();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC20:  (SpeedCalcButton.focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed.speedCalcButton_FocusGained(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC20(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedCalcButton_FocusGained(arg1);
		connEtoM22();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC21:  (SpeedCalcButton.focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed.speedCalcButton_FocusLost(Ljava.awt.event.FocusEvent;)V)
 * @param arg1 java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC21(java.awt.event.FocusEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedCalcButton_FocusLost(arg1);
		connEtoM23();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC3:  (SpeedField.mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed.speedField_MouseEntered(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC3(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedField_MouseEntered(arg1);
		connEtoM9();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC4:  (FactorField.mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed.factorField_MouseEntered(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC4(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.factorField_MouseEntered(arg1);
		connEtoM10();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC5:  (LengthAtWaterLineField.mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed.lengthAtWaterLineField_MouseEntered(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC5(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.lengthAtWaterLineField_MouseEntered(arg1);
		connEtoM11();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC6:  (LengthAtWaterLineField.mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed.lengthAtWaterLineField_MouseExited(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC6(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.lengthAtWaterLineField_MouseExited(arg1);
		connEtoM8();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC7:  (FactorField.mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed.factorField_MouseExited(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC7(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.factorField_MouseExited(arg1);
		connEtoM7();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC8:  (SpeedField.mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed.speedField_MouseExited(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC8(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedField_MouseExited(arg1);
		connEtoM6();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoC9:  (SpeedFieldMPH.mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed.speedFieldMPH_MouseExited(Ljava.awt.event.MouseEvent;)V)
 * @param arg1 java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoC9(java.awt.event.MouseEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		this.speedFieldMPH_MouseExited(arg1);
		connEtoM5();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM1:  (Button1.action.actionPerformed(java.awt.event.ActionEvent) --> Calculator.add()V)
 * @param arg1 java.awt.event.ActionEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM1(java.awt.event.ActionEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		getCalculator().add();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM10:  ( (FactorField,mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed,factorField_MouseEntered(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM10() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getFactorMsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM11:  ( (LengthAtWaterLineField,mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed,lengthAtWaterLineField_MouseEntered(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM11() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getLWLmsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM12:  ( (LengthAtWaterLineField,focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed,lengthAtWaterLineField_FocusGained3(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM12() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getLWLmsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM13:  ( (LengthAtWaterLineField,focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed,lengthAtWaterLineField_FocusLost1(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM13() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM14:  ( (FactorField,focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed,factorField_FocusLost(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM14() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM15:  ( (FactorField,focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed,factorField_FocusGained(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM15() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getSpeedKnotsMsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM16:  ( (SpeedField,focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed,speedField_FocusGained(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM16() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getFactorMsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM17:  ( (SpeedField,focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed,speedField_FocusLost(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM17() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM18:  ( (SpeedFieldMPH,focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed,speedFieldMPH_FocusGained(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM18() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getSpeedMPHmsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM19:  ( (SpeedFieldMPH,focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed,speedFieldMPH_FocusLost(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM19() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM2:  (SpeedCalcButton.action.actionPerformed(java.awt.event.ActionEvent) --> Calculator.speed()V)
 * @param arg1 java.awt.event.ActionEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM2(java.awt.event.ActionEvent arg1) {
	try {
		// user code begin {1}
		// user code end
		getCalculator().speed();
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM20:  ( (SpeedCalcButton,mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed,speedCalcButton_MouseEntered(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM20() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getCalculateButtonMouseMsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM21:  ( (SpeedFieldMPH,mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed,speedFieldMPH_MouseExited1(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM21() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM22:  ( (SpeedCalcButton,focus.focusGained(java.awt.event.FocusEvent) --> HulSpeed,speedCalcButton_FocusGained(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM22() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getCalculateButtonTabMsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM23:  ( (SpeedCalcButton,focus.focusLost(java.awt.event.FocusEvent) --> HulSpeed,speedCalcButton_FocusLost(Ljava.awt.event.FocusEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM23() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(new java.lang.String());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM3:  ( (SpeedField,text.textValueChanged(java.awt.event.TextEvent) --> HulSpeed,speedField_TextValueChanged1(Ljava.awt.event.TextEvent;)V).normalResult --> Calculator.fieldResultMPH)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM3() {
	try {
		// user code begin {1}
		// user code end
		getSpeedFieldMPH().setText(String.valueOf(getCalculator().getFieldResultMPH()));
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * Comment
 */
public void connEtoM3_NormalResult() {
	return;
}
/**
 * Comment
 */
public void connEtoM3_NormalResult1() {
	return;
}
/**
 * Comment
 */
public java.lang.String connEtoM3_Value() {
	return "0.0";
}
/**
 * connEtoM4:  ( (SpeedFieldMPH,mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed,speedFieldMPH_MouseEntered1(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM4() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getSpeedMPHmsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * Comment
 */
public java.lang.String connEtoM4_Text() {
	return "1.15 * Speed in knots";
}
/**
 * connEtoM5:  ( (SpeedFieldMPH,mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed,speedFieldMPH_MouseExited(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM5() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM6:  ( (SpeedField,mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed,speedField_MouseExited(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM6() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM7:  ( (FactorField,mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed,factorField_MouseExited(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM7() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM8:  ( (LengthAtWaterLineField,mouse.mouseExited(java.awt.event.MouseEvent) --> HulSpeed,lengthAtWaterLineField_MouseExited(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM8() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getblank().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connEtoM9:  ( (SpeedField,mouse.mouseEntered(java.awt.event.MouseEvent) --> HulSpeed,speedField_MouseEntered(Ljava.awt.event.MouseEvent;)V).normalResult --> msgField.text)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connEtoM9() {
	try {
		// user code begin {1}
		// user code end
		getmsgField().setText(getSpeedKnotsMsg().getText());
		// user code begin {2}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connPtoP1SetSource:  (SpeedField.text <--> Calculator.result)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connPtoP1SetSource() {
	/* Set the source from the target */
	try {
		getSpeedField().setText(String.valueOf(getCalculator().getResult()));
		// user code begin {1}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * connPtoP1SetTarget:  (SpeedField.text <--> Calculator.result)
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void connPtoP1SetTarget() {
	/* Set the target from the source */
	try {
		getCalculator().setResult(new Double(getSpeedField().getText()).doubleValue());
		// user code begin {1}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {3}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * Comment
 */
public void factorField_FocusGained(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void factorField_FocusLost(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void factorField_MouseEntered(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void factorField_MouseExited(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * The firePropertyChange method was generated to support the propertyChange field.
 */
public void firePropertyChange(java.lang.String propertyName, java.lang.Object oldValue, java.lang.Object newValue) {
	getPropertyChange().firePropertyChange(propertyName, oldValue, newValue);
}
/**
 * Method to handle events for the FocusListener interface.
 * @param e java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void focusGained(java.awt.event.FocusEvent e) {
	// user code begin {1}
	// user code end
	if (e.getSource() == getLengthAtWaterLineField()) 
		connEtoC2(e);
	if (e.getSource() == getFactorField()) 
		connEtoC12(e);
	if (e.getSource() == getSpeedField()) 
		connEtoC14(e);
	if (e.getSource() == getSpeedFieldMPH()) 
		connEtoC16(e);
	if (e.getSource() == getSpeedCalcButton()) 
		connEtoC20(e);
	// user code begin {2}
	// user code end
}
/**
 * Method to handle events for the FocusListener interface.
 * @param e java.awt.event.FocusEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void focusLost(java.awt.event.FocusEvent e) {
	// user code begin {1}
	// user code end
	if (e.getSource() == getLengthAtWaterLineField()) 
		connEtoC11(e);
	if (e.getSource() == getFactorField()) 
		connEtoC13(e);
	if (e.getSource() == getSpeedField()) 
		connEtoC15(e);
	if (e.getSource() == getSpeedFieldMPH()) 
		connEtoC17(e);
	if (e.getSource() == getSpeedCalcButton()) 
		connEtoC21(e);
	// user code begin {2}
	// user code end
}
/**
 * Return the Button1 property value.
 * @return java.awt.Button
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Button getAddButton() {
	if (ivjAddButton == null) {
		try {
			ivjAddButton = new java.awt.Button();
			ivjAddButton.setName("AddButton");
			ivjAddButton.setFont(new java.awt.Font("dialog", 1, 20));
			ivjAddButton.setBounds(18, 203, 35, 32);
			ivjAddButton.setVisible(false);
			ivjAddButton.setLabel("+");
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjAddButton;
}
/**
 * Gets the applet information.
 * @return java.lang.String
 */
public String getAppletInfo() {
	return "ch11.Toto created using VisualAge for Java.";
}
/**
 * Return the blank property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getblank() {
	if (ivjblank == null) {
		try {
			ivjblank = new java.awt.Label();
			ivjblank.setName("blank");
			ivjblank.setText("");
			ivjblank.setBounds(819, 211, 52, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjblank;
}
/**
 * Return the CalculateButtonMouseMsg property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getCalculateButtonMouseMsg() {
	if (ivjCalculateButtonMouseMsg == null) {
		try {
			ivjCalculateButtonMouseMsg = new java.awt.Label();
			ivjCalculateButtonMouseMsg.setName("CalculateButtonMouseMsg");
			ivjCalculateButtonMouseMsg.setText("click mouse to calculate speed");
			ivjCalculateButtonMouseMsg.setBounds(742, 518, 207, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjCalculateButtonMouseMsg;
}
/**
 * Return the CalculateButtonTabMsg property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getCalculateButtonTabMsg() {
	if (ivjCalculateButtonTabMsg == null) {
		try {
			ivjCalculateButtonTabMsg = new java.awt.Label();
			ivjCalculateButtonTabMsg.setName("CalculateButtonTabMsg");
			ivjCalculateButtonTabMsg.setText("press space bar to calculate speed");
			ivjCalculateButtonTabMsg.setBounds(749, 585, 228, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjCalculateButtonTabMsg;
}
/**
 * Return the Calculator property value.
 * @return ch11.Calculator
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private Calculator getCalculator() {
	if (ivjCalculator == null) {
		try {
			ivjCalculator = new ch11.Calculator();
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjCalculator;
}
/**
 * Return the Button13 property value.
 * @return java.awt.Button
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Button getDivideButton() {
	if (ivjDivideButton == null) {
		try {
			ivjDivideButton = new java.awt.Button();
			ivjDivideButton.setName("DivideButton");
			ivjDivideButton.setFont(new java.awt.Font("dialog", 1, 20));
			ivjDivideButton.setBounds(313, 264, 35, 32);
			ivjDivideButton.setVisible(false);
			ivjDivideButton.setLabel("/");
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjDivideButton;
}
/**
 * Return the TextField2 property value.
 * @return java.awt.TextField
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.TextField getFactorField() {
	if (ivjFactorField == null) {
		try {
			ivjFactorField = new java.awt.TextField();
			ivjFactorField.setName("FactorField");
			ivjFactorField.setFont(new java.awt.Font("dialog", 1, 14));
			ivjFactorField.setText("1.34");
			ivjFactorField.setBounds(88, 81, 160, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjFactorField;
}
/**
 * Return the Label11 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getFactorFieldLable() {
	if (ivjFactorFieldLable == null) {
		try {
			ivjFactorFieldLable = new java.awt.Label();
			ivjFactorFieldLable.setName("FactorFieldLable");
			ivjFactorFieldLable.setFont(new java.awt.Font("dialog", 1, 16));
			ivjFactorFieldLable.setText("Factor");
			ivjFactorFieldLable.setBounds(19, 81, 52, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjFactorFieldLable;
}
/**
 * Return the FactorMsg property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getFactorMsg() {
	if (ivjFactorMsg == null) {
		try {
			ivjFactorMsg = new java.awt.Label();
			ivjFactorMsg.setName("FactorMsg");
			ivjFactorMsg.setText("enter value - usually 1.34");
			ivjFactorMsg.setBounds(659, 340, 199, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjFactorMsg;
}
/**
 * Return the Label1 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getLenghtAtWaterLineLable() {
	if (ivjLenghtAtWaterLineLable == null) {
		try {
			ivjLenghtAtWaterLineLable = new java.awt.Label();
			ivjLenghtAtWaterLineLable.setName("LenghtAtWaterLineLable");
			ivjLenghtAtWaterLineLable.setFont(new java.awt.Font("dialog", 1, 16));
			ivjLenghtAtWaterLineLable.setText("LWL");
			ivjLenghtAtWaterLineLable.setBounds(35, 47, 36, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjLenghtAtWaterLineLable;
}
/**
 * Return the LenghtAtWaterLineLable2 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getLenghtAtWaterLineLable2() {
	if (ivjLenghtAtWaterLineLable2 == null) {
		try {
			ivjLenghtAtWaterLineLable2 = new java.awt.Label();
			ivjLenghtAtWaterLineLable2.setName("LenghtAtWaterLineLable2");
			ivjLenghtAtWaterLineLable2.setFont(new java.awt.Font("dialog", 1, 16));
			ivjLenghtAtWaterLineLable2.setText("Feet");
			ivjLenghtAtWaterLineLable2.setBounds(261, 47, 41, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjLenghtAtWaterLineLable2;
}
/**
 * Return the TextField1 property value.
 * @return java.awt.TextField
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.TextField getLengthAtWaterLineField() {
	if (ivjLengthAtWaterLineField == null) {
		try {
			ivjLengthAtWaterLineField = new java.awt.TextField();
			ivjLengthAtWaterLineField.setName("LengthAtWaterLineField");
			ivjLengthAtWaterLineField.setFont(new java.awt.Font("dialog", 1, 14));
			ivjLengthAtWaterLineField.setText("22");
			ivjLengthAtWaterLineField.setBounds(88, 47, 160, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjLengthAtWaterLineField;
}
/**
 * Return the LWLmsg property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getLWLmsg() {
	if (ivjLWLmsg == null) {
		try {
			ivjLWLmsg = new java.awt.Label();
			ivjLWLmsg.setName("LWLmsg");
			ivjLWLmsg.setText("enter length at water line - 22 for MAC26x");
			ivjLWLmsg.setBounds(617, 278, 234, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjLWLmsg;
}
/**
 * Return the msgField property value.
 * @return java.awt.TextField
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.TextField getmsgField() {
	if (ivjmsgField == null) {
		try {
			ivjmsgField = new java.awt.TextField();
			ivjmsgField.setName("msgField");
			ivjmsgField.setFont(new java.awt.Font("dialog", 0, 14));
			ivjmsgField.setBounds(28, 242, 274, 23);
			ivjmsgField.setEditable(false);
			ivjmsgField.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjmsgField;
}
/**
 * Return the Button12 property value.
 * @return java.awt.Button
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Button getMultiplyButton() {
	if (ivjMultiplyButton == null) {
		try {
			ivjMultiplyButton = new java.awt.Button();
			ivjMultiplyButton.setName("MultiplyButton");
			ivjMultiplyButton.setFont(new java.awt.Font("dialog", 1, 20));
			ivjMultiplyButton.setBounds(259, 268, 35, 32);
			ivjMultiplyButton.setVisible(false);
			ivjMultiplyButton.setLabel("X");
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjMultiplyButton;
}
/**
 * Accessor for the propertyChange field.
 */
protected java.beans.PropertyChangeSupport getPropertyChange() {
	if (propertyChange == null) {
		propertyChange = new java.beans.PropertyChangeSupport(this);
	};
	return propertyChange;
}
/**
 * Return the SpeedCalcButton property value.
 * @return java.awt.Button
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Button getSpeedCalcButton() {
	if (ivjSpeedCalcButton == null) {
		try {
			ivjSpeedCalcButton = new java.awt.Button();
			ivjSpeedCalcButton.setName("SpeedCalcButton");
			ivjSpeedCalcButton.setBounds(89, 189, 160, 30);
			ivjSpeedCalcButton.setLabel("Press to Calculate Speed");
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedCalcButton;
}
/**
 * Return the TextField3 property value.
 * @return java.awt.TextField
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.TextField getSpeedField() {
	if (ivjSpeedField == null) {
		try {
			ivjSpeedField = new java.awt.TextField();
			ivjSpeedField.setName("SpeedField");
			ivjSpeedField.setFont(new java.awt.Font("dialog", 1, 14));
			ivjSpeedField.setBounds(88, 113, 160, 23);
			ivjSpeedField.setEditable(false);
			ivjSpeedField.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedField;
}
/**
 * Return the SpeedFieldLabel1 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getSpeedFieldLabel1() {
	if (ivjSpeedFieldLabel1 == null) {
		try {
			ivjSpeedFieldLabel1 = new java.awt.Label();
			ivjSpeedFieldLabel1.setName("SpeedFieldLabel1");
			ivjSpeedFieldLabel1.setFont(new java.awt.Font("dialog", 1, 16));
			ivjSpeedFieldLabel1.setText("Speed");
			ivjSpeedFieldLabel1.setBounds(19, 153, 51, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedFieldLabel1;
}
/**
 * Return the Label12 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getSpeedFieldLabel12() {
	if (ivjSpeedFieldLabel12 == null) {
		try {
			ivjSpeedFieldLabel12 = new java.awt.Label();
			ivjSpeedFieldLabel12.setName("SpeedFieldLabel12");
			ivjSpeedFieldLabel12.setFont(new java.awt.Font("dialog", 1, 16));
			ivjSpeedFieldLabel12.setText("Speed");
			ivjSpeedFieldLabel12.setBounds(18, 113, 53, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedFieldLabel12;
}
/**
 * Return the SpeedFieldLabel2 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getSpeedFieldLabel2() {
	if (ivjSpeedFieldLabel2 == null) {
		try {
			ivjSpeedFieldLabel2 = new java.awt.Label();
			ivjSpeedFieldLabel2.setName("SpeedFieldLabel2");
			ivjSpeedFieldLabel2.setFont(new java.awt.Font("dialog", 1, 16));
			ivjSpeedFieldLabel2.setText("Knots");
			ivjSpeedFieldLabel2.setBounds(263, 113, 52, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedFieldLabel2;
}
/**
 * Return the SpeedFieldLabel22 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getSpeedFieldLabel22() {
	if (ivjSpeedFieldLabel22 == null) {
		try {
			ivjSpeedFieldLabel22 = new java.awt.Label();
			ivjSpeedFieldLabel22.setName("SpeedFieldLabel22");
			ivjSpeedFieldLabel22.setFont(new java.awt.Font("dialog", 1, 16));
			ivjSpeedFieldLabel22.setText("MPH");
			ivjSpeedFieldLabel22.setBounds(263, 153, 52, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedFieldLabel22;
}
/**
 * Return the SpeedFieldMPH property value.
 * @return java.awt.TextField
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.TextField getSpeedFieldMPH() {
	if (ivjSpeedFieldMPH == null) {
		try {
			ivjSpeedFieldMPH = new java.awt.TextField();
			ivjSpeedFieldMPH.setName("SpeedFieldMPH");
			ivjSpeedFieldMPH.setFont(new java.awt.Font("dialog", 1, 14));
			ivjSpeedFieldMPH.setBounds(88, 153, 160, 23);
			ivjSpeedFieldMPH.setEditable(false);
			ivjSpeedFieldMPH.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedFieldMPH;
}
/**
 * Return the SpeedKnotsMsg property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getSpeedKnotsMsg() {
	if (ivjSpeedKnotsMsg == null) {
		try {
			ivjSpeedKnotsMsg = new java.awt.Label();
			ivjSpeedKnotsMsg.setName("SpeedKnotsMsg");
			ivjSpeedKnotsMsg.setText("Factor * square root of LWL");
			ivjSpeedKnotsMsg.setBounds(475, 355, 153, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedKnotsMsg;
}
/**
 * Return the Label1 property value.
 * @return java.awt.Label
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Label getSpeedMPHmsg() {
	if (ivjSpeedMPHmsg == null) {
		try {
			ivjSpeedMPHmsg = new java.awt.Label();
			ivjSpeedMPHmsg.setName("SpeedMPHmsg");
			ivjSpeedMPHmsg.setText("1.15 * speed in knots");
			ivjSpeedMPHmsg.setBounds(591, 392, 220, 23);
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSpeedMPHmsg;
}
/**
 * Return the Button11 property value.
 * @return java.awt.Button
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private java.awt.Button getSubtactButton() {
	if (ivjSubtactButton == null) {
		try {
			ivjSubtactButton = new java.awt.Button();
			ivjSubtactButton.setName("SubtactButton");
			ivjSubtactButton.setFont(new java.awt.Font("dialog", 1, 20));
			ivjSubtactButton.setBounds(22, 244, 35, 32);
			ivjSubtactButton.setVisible(false);
			ivjSubtactButton.setLabel("-");
			// user code begin {1}
			// user code end
		} catch (java.lang.Throwable ivjExc) {
			// user code begin {2}
			// user code end
			handleException(ivjExc);
		}
	}
	return ivjSubtactButton;
}
/**
 * Called whenever the part throws an exception.
 * @param exception java.lang.Throwable
 */
private void handleException(Throwable exception) {

	/* Uncomment the following lines to print uncaught exceptions to stdout */
	// System.out.println("--------- UNCAUGHT EXCEPTION ---------");
	// exception.printStackTrace(System.out);
}
/**
 * Handle the Applet init method.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void init() {
	try {
		super.init();
		setName("Toto");
		setLayout(null);
		setSize(331, 308);
		add(getLenghtAtWaterLineLable(), getLenghtAtWaterLineLable().getName());
		add(getSpeedCalcButton(), getSpeedCalcButton().getName());
		add(getmsgField(), getmsgField().getName());
		add(getLengthAtWaterLineField(), getLengthAtWaterLineField().getName());
		add(getLenghtAtWaterLineLable2(), getLenghtAtWaterLineLable2().getName());
		add(getFactorFieldLable(), getFactorFieldLable().getName());
		add(getFactorField(), getFactorField().getName());
		add(getSpeedFieldLabel12(), getSpeedFieldLabel12().getName());
		add(getSpeedField(), getSpeedField().getName());
		add(getSpeedFieldLabel2(), getSpeedFieldLabel2().getName());
		add(getSpeedFieldLabel1(), getSpeedFieldLabel1().getName());
		add(getSpeedFieldMPH(), getSpeedFieldMPH().getName());
		add(getSpeedFieldLabel22(), getSpeedFieldLabel22().getName());
		add(getAddButton(), getAddButton().getName());
		add(getSubtactButton(), getSubtactButton().getName());
		add(getDivideButton(), getDivideButton().getName());
		add(getMultiplyButton(), getMultiplyButton().getName());
		initConnections();
		// user code begin {1}
		// user code end
	} catch (java.lang.Throwable ivjExc) {
		// user code begin {2}
		// user code end
		handleException(ivjExc);
	}
}
/**
 * Initializes connections
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void initConnections() throws java.lang.Exception {
	// user code begin {1}
	// user code end
	getLengthAtWaterLineField().addTextListener(this);
	getCalculator().addPropertyChangeListener(this);
	getFactorField().addTextListener(this);
	getDivideButton().addActionListener(this);
	getMultiplyButton().addActionListener(this);
	getSubtactButton().addActionListener(this);
	getAddButton().addActionListener(this);
	getSpeedField().addMouseListener(this);
	getFactorField().addMouseListener(this);
	getLengthAtWaterLineField().addMouseListener(this);
	getSpeedFieldMPH().addMouseListener(this);
	getLengthAtWaterLineField().addFocusListener(this);
	getFactorField().addFocusListener(this);
	getSpeedField().addFocusListener(this);
	getSpeedFieldMPH().addFocusListener(this);
	getSpeedCalcButton().addMouseListener(this);
	getSpeedCalcButton().addFocusListener(this);
	getSpeedCalcButton().addActionListener(this);
	getSpeedField().addTextListener(this);
	conn0SetTarget();
	conn1SetTarget();
	connPtoP1SetTarget();
}
/**
 * Comment
 */
public void lengthAtWaterLineField_FocusGained(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void lengthAtWaterLineField_FocusGained1(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void lengthAtWaterLineField_FocusGained2(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void lengthAtWaterLineField_FocusGained3(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void lengthAtWaterLineField_FocusLost(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void lengthAtWaterLineField_FocusLost1(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void lengthAtWaterLineField_MouseEntered(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void lengthAtWaterLineField_MouseExited(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * main entrypoint - starts the part when it is run as an application
 * @param args java.lang.String[]
 */
public static void main(java.lang.String[] args) {
	try {
		java.awt.Frame frame;
		try {
			Class aFrameClass = Class.forName("uvm.abt.edit.TestFrame");
			frame = (java.awt.Frame)aFrameClass.newInstance();
		} catch (java.lang.Throwable ivjExc) {
			frame = new java.awt.Frame();
		}
		ch11.CalculApplet aCalculApplet = new ch11.CalculApplet();
		frame.add("Center", aCalculApplet);
		frame.setSize(aCalculApplet.getSize());
		aCalculApplet.init();
		aCalculApplet.start();
		frame.setVisible(true);

		aCalculApplet.destroy();
	} catch (Throwable exception) {
		System.err.println("Exception occurred in main() of java.applet.Applet");
	}
}
/**
 * Method to handle events for the MouseListener interface.
 * @param e java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void mouseClicked(java.awt.event.MouseEvent e) {
	// user code begin {1}
	// user code end
	// user code begin {2}
	// user code end
}
/**
 * Method to handle events for the MouseListener interface.
 * @param e java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void mouseEntered(java.awt.event.MouseEvent e) {
	// user code begin {1}
	// user code end
	if (e.getSource() == getSpeedField()) 
		connEtoC3(e);
	if (e.getSource() == getFactorField()) 
		connEtoC4(e);
	if (e.getSource() == getLengthAtWaterLineField()) 
		connEtoC5(e);
	if (e.getSource() == getSpeedFieldMPH()) 
		connEtoC10(e);
	if (e.getSource() == getSpeedCalcButton()) 
		connEtoC18(e);
	// user code begin {2}
	// user code end
}
/**
 * Method to handle events for the MouseListener interface.
 * @param e java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void mouseExited(java.awt.event.MouseEvent e) {
	// user code begin {1}
	// user code end
	if (e.getSource() == getLengthAtWaterLineField()) 
		connEtoC6(e);
	if (e.getSource() == getFactorField()) 
		connEtoC7(e);
	if (e.getSource() == getSpeedField()) 
		connEtoC8(e);
	if (e.getSource() == getSpeedFieldMPH()) 
		connEtoC9(e);
	if (e.getSource() == getSpeedCalcButton()) 
		connEtoC19(e);
	// user code begin {2}
	// user code end
}
/**
 * Method to handle events for the MouseListener interface.
 * @param e java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void mousePressed(java.awt.event.MouseEvent e) {
	// user code begin {1}
	// user code end
	// user code begin {2}
	// user code end
}
/**
 * Method to handle events for the MouseListener interface.
 * @param e java.awt.event.MouseEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void mouseReleased(java.awt.event.MouseEvent e) {
	// user code begin {1}
	// user code end
	// user code begin {2}
	// user code end
}
/**
 * Method to handle events for the PropertyChangeListener interface.
 * @param evt java.beans.PropertyChangeEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void propertyChange(java.beans.PropertyChangeEvent evt) {
	// user code begin {1}
	// user code end
	if (evt.getSource() == getCalculator() && (evt.getPropertyName().equals("num1"))) 
		conn0SetSource();
	if (evt.getSource() == getCalculator() && (evt.getPropertyName().equals("num2"))) 
		conn1SetSource();
	if (evt.getSource() == getCalculator() && (evt.getPropertyName().equals("result"))) 
		connPtoP1SetSource();
	// user code begin {2}
	// user code end
}
/**
 * The removePropertyChangeListener method was generated to support the propertyChange field.
 */
public synchronized void removePropertyChangeListener(java.beans.PropertyChangeListener listener) {
	getPropertyChange().removePropertyChangeListener(listener);
}
/**
 * Comment
 */
public void speedCalcButton_ActionPerformed(java.awt.event.ActionEvent actionEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_ActionPerformed1(java.awt.event.ActionEvent actionEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_FocusGained(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_FocusLost(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_KeyPressed(java.awt.event.KeyEvent keyEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_MouseEntered(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_MouseExited(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_MousePressed(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_MousePressed1(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedCalcButton_MousePressed2(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedField_FocusGained(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void speedField_FocusLost(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void speedField_MouseEntered(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedField_MouseExited(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedField_TextValueChanged(java.awt.event.TextEvent textEvent) {
	return;
}
/**
 * Comment
 */
public void speedField_TextValueChanged1(java.awt.event.TextEvent textEvent) {
	return;
}
/**
 * Comment
 */
public void speedFieldMPH_FocusGained(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void speedFieldMPH_FocusLost(java.awt.event.FocusEvent focusEvent) {
	return;
}
/**
 * Comment
 */
public void speedFieldMPH_MouseEntered(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedFieldMPH_MouseEntered1(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedFieldMPH_MouseExited(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Comment
 */
public void speedFieldMPH_MouseExited1(java.awt.event.MouseEvent mouseEvent) {
	return;
}
/**
 * Method to handle events for the TextListener interface.
 * @param e java.awt.event.TextEvent
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void textValueChanged(java.awt.event.TextEvent e) {
	// user code begin {1}
	// user code end
	if (e.getSource() == getLengthAtWaterLineField()) 
		conn0SetTarget();
	if (e.getSource() == getFactorField()) 
		conn1SetTarget();
	if (e.getSource() == getSpeedField()) 
		connEtoC1(e);
	// user code begin {2}
	// user code end
}
}
